#!/usr/bin/python3
#
# suggested usage: get_meeting_info | xmlstarlet fo

from lxml import etree
import subprocess

from vnc_collaborate import bigbluebutton

xml = etree.tostring(bigbluebutton.getMeetings())

xmlstarlet = subprocess.Popen(['xmlstarlet', 'fo'], stdin=subprocess.PIPE)
xmlstarlet.communicate(xml)

