#!/usr/bin/python3
#
# Usage: ./list-logins < /var/log/bigbluebutton/bbb-web.2020-05-06.log

import sys
import re
import json
import dateutil.parser
import datetime
from dateutil import tz

re_line = re.compile('^(\S*).*data=(.*user_.*)$')

for line in sys.stdin:
    m = re.match(re_line, line)
    if m:
        j = json.loads(m.group(2))
        if j['logCode'] in ('user_left_message', 'user_joined_message'):
            timestamp = dateutil.parser.parse(m.group(1)).replace(tzinfo = datetime.timezone.utc)
            timestr = timestamp.astimezone(tz.tzlocal()).strftime("%b %d %I:%M:%S %p %Z")
            print('{:20} {:30} {}'.format(timestr, j['logCode'], j['username']))
