#!/usr/bin/python3
#
# Feed all or part of app log from Microsoft authentication app
# to figure out who logged in and when.
#
# I've since realized that the Microsoft authentication app
# makes log entries even when people are not logged in.
#
# Not sure why, but use list-logins-2 instead.

import sys
import json
import json5

#f = open('/home/baccala/.pm2/logs/app-out.log')
s = sys.stdin.read()
#f.close()

lines = s.split('\n')

for l in lines:
    if l.startswith('{'):
        j = json.loads(l)
        msg = j['msg']
        if msg.startswith('we are using user: '):
            msg = msg.replace('we are using user: ', '').strip()
            try:
                j2 = json5.loads(msg.replace('undefined', '\'undefined\''))
                if 'name' in j2['_json']:
                    print(j['time'], j2['_json']['name'])
                elif 'preferred_username' in j2['_json']:
                    print(j['time'], j2['_json']['preferred_username'])
                else:
                    print(j['time'], '????')

            except Exception as e:
                print(e)
                print(msg)
                break
