#! /bin/bash
#
# Usage: start-vnc-desktop MAX-DIMENSION MIN-DIMENSION IS-TEACHER-FLAG X-DESKTOP-NUMBER USER-NAME

if [ $3 != "true" ]; then

    # Student version

    # I've had enough problems with scaling the student desktop geometry that
    # I now fix it at 1000x600

    #XDIM=$1
    #YDIM=$2
    XDIM=1000
    YDIM=600
    TEACHER_FLAG=$3
    XDISPLAY=$4
    USERNAME=$5

    USER=`echo $USERNAME | sed 's/ //g'`       # squash spaces

    if grep -q ^${USER}: /etc/passwd; then
        echo found
    else
        # student does not exist
	sudo adduser --gecos ${USER} --disabled-login --force-badname ${USER}
    fi

    ARGS="$XDIM $YDIM $TEACHER_FLAG $XDISPLAY $USER"

    # start monitoring Xvnc log file (which hasn't been created yet) to track number of connections
    # and record the number in a SQL database
    /home/baccala/src/osito/monitor-vnc-log /home/${USER}/.vnc/osito\:${XDISPLAY}.log &

    sudo su ${USER} -c "STARTUP=\"/home/baccala/src/osito/student-desktop $ARGS\" vncserver -geometry ${XDIM}x${YDIM} :${XDISPLAY}"

else

    # Teacher version
    STARTUP="/home/baccala/src/osito/teacher-desktop $*" vncserver -geometry ${1}x${2} :${4}

fi

