#! /bin/bash
#
# Usage: start-vnc-desktop MAX-DIMENSION MIN-DIMENSION IS-TEACHER-FLAG X-DESKTOP-NUMBER

vncserver -geometry ${1}x${2} :${4}

export DISPLAY=:${4}

if [ $3 != "true" ]; then

    # Student version

    firefox -no-remote http://www.geogebra.org/geometry &

    while ! bwb=`xwininfo  -root -children | grep Navigator`; do
	sleep 1
    done

    id=`echo $bwb | sed 's/^ *//' | cut -d ' ' -f 1`

    xwit -id $id -resize $1 $2

else

    # Teacher version
    exec ~/src/osito/teacher-desktop

fi

