#! /bin/bash
#
# Usage: start-vnc-desktop MAX-DIMENSION MIN-DIMENSION IS-TEACHER-FLAG X-DESKTOP-NUMBER USER-NAME

if [ $3 != "true" ]; then

    # Student version

    USER=`echo $5 | sed 's/ //g'`       # squash spaces

    if grep -q ^${USER}: /etc/passwd; then
        echo found
    else
        # student does not exist
	sudo adduser --gecos ${USER} --disabled-login --force-badname ${USER}
    fi

    sudo su ${USER} -c "/home/baccala/src/osito/student-desktop $1 $2 $3 $4 $5"

else

    # Teacher version
    STARTUP="/home/baccala/src/osito/teacher-desktop $*" vncserver -geometry ${1}x${2} :${4}

fi

