#! /usr/bin/python3

import sys
import re
import subprocess

import freeswitch

match = re.search(r'([^ ]*)\\\'s X desktop \((osito:[0-9]*)', sys.argv[1])

if match:

   STUDENT = match.group(1)
   STUDENT_DISPLAY = match.group(2)

   print(STUDENT, STUDENT_DISPLAY)

   freeswitch.unmute_student(STUDENT)

   # XXX Teacher desktop geometry is hard-wired here!

   args = ['ssvncviewer', '-title', 'Zoomed Student Desktop',
           '-geometry', '1476x830', '-scale', '1476x830',
           '-escape', 'Alt_L', '-passwd', '/home/baccala/.vnc/passwd',
           STUDENT_DISPLAY]
   print(args)

   proc = subprocess.Popen(args)
   proc.wait()

   freeswitch.mute_student(STUDENT)
