#! /usr/bin/python3

import sys
import re
import subprocess

match = re.search(r'osito:[0-9]*', sys.argv[1])

if match:

   STUDENT_DISPLAY = match.group(0)

   # XXX Teacher desktop geometry is hard-wired here!

   proc = subprocess.Popen(['ssvncviewer', '-title', 'Zoomed Student Desktop',
                            '-geometry', '1476x830', '-scale', '1476x830',
                            '-escape', 'Alt_L', '-passwd', '/home/baccala/.vnc/passwd',
                            STUDENT_DISPLAY])

   proc.wait()
