#!/usr/bin/python3
#
# Unmutes (and undeafs) a list of students (the names should be squashed, i.e, no spaces)

import sys
import freeswitch

if len(sys.argv) < 2:
    print("Specify at least one student name, or -a for all")
elif sys.argv[1] == '-a':
    freeswitch.undeaf_all()
else:
    for student in sys.argv[1:]:
        freeswitch.undeaf_student(student)
