#!/usr/bin/python3
#
# Unmutes (and undeafs) a list of students (the names should be squashed, i.e, no spaces)

import sys
import freeswitch

for student in sys.argv[1:]:       
    freeswitch.unmute_student(student)
