#! /usr/bin/python3

from vnc_collaborate import vnc
import glob

for fn in glob.glob('/run/vnc/*'):
    VNCdata = vnc.get_VNC_info(fn)
    for k,v in VNCdata.items():
        print('{:25} {:8} {}'.format(fn,k,v))
